import { 
  Home,
  Search,
  PlusCircle,
  MessageCircle,
  User,
  Eye,
  Heart,
  Share2,
  MessageSquare,
  ArrowLeft,
  Send,
  Video,
  Volume2,
  Plus,
  Settings,
  Camera,
  MapPin,
  Layers,
  Navigation,
  RefreshCw,
  Edit,
  Trash,
  Bookmark,
  Play,
  Pause,
  Maximize,
  type Icon as LucideIcon,
  AlertTriangle,
} from 'lucide-react-native';

export type Icon = LucideIcon;

export const Icons = {
  home: Home,
  search: Search,
  upload: PlusCircle,
  messages: MessageCircle,
  user: User,
  eye: Eye,
  heart: Heart,
  share: Share2,
  comment: MessageSquare,
  back: ArrowLeft,
  send: Send,
  video: Video,
  volume2: Volume2,
  plus: Plus,
  settings: Settings,
  camera: Camera,
  mapPin: MapPin,
  layers: Layers,
  navigation: Navigation,
  refresh: RefreshCw,
  edit: Edit,
  trash: Trash,
  bookmark: Bookmark,
  play: Play,
  pause: Pause,
  maximize: Maximize,
  alert: AlertTriangle,
} as const;